server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:localhost.p12
    key-store-password: "Ss22/12/2004" # Use the same export password you set when creating the PKCS#12 file
    key-store-type: PKCS12
  http2:
    enabled: true